{
  "en": {

    "nav": {
      "decks": "Колоды",
      "importCards": "Импорт карточек",
      "progress": "Прогресс",
      "projectSettings": "Настройки проекта",
      "spacedRepetition": "Spaced Repetition",
      "sendFeedback": "Отправить отзыв"
    },

    "bottomNav": {
      "decks": "Колоды",
      "import": "Импорт",
      "progress": "Прогресс",
      "settings": "Настройки"
    },

    "auth": {
      "subtitle": "Spaced Repetition System"
    },

    "deckList": {
      "allDecksReview": "All decks Review",
      "dueToday": "{n} due today, {m} new cards",
      "startReview": "Start Review",
      "yourDecks": "Your Decks",
      "newDeck": "New Deck",
      "cards": "{n} cards",
      "due": "{n} due",
      "new_badge": "{n} new",
      "starred": "{n} starred",
      "off": "{n} off",
      "study": "Study",
      "practiceMode": "Practice mode",
      "tipsHeading": "Shape an effective learning curve",
      "tip1": "Creating a deck with 20-30 cards is ideal for learning.",
      "tip2": "If you have more than 30, divide them into decks based on complexity.",
      "tip3": "Begin learning 20 cards a week to get accustomed to the process.",
      "tip4": "Use Weekend mode for intensive learning.",
      "tip5": "Import your cards via CSV mapping or enter them manually.",
      "addADeck": "Add a deck",
      "decksLibrary": "Decks Library",
      "createDeck": "Create New Deck",
      "createDeckDesc": "Create a new deck to organize your flashcards.",
      "editDeck": "Edit Deck",
      "saveChanges": "Save Changes",
      "deleteDeck": "Delete Deck?",
      "deleteDeckDesc": "This will permanently delete \"{name}\" and all its cards. This action cannot be undone.",
      "delete": "Delete",
      "cancel": "Cancel",
      "deckName": "Name *",
      "deckLanguage": "Language *",
      "deckDescription": "Description (optional)",
      "deckNamePlaceholder": "e.g., Week 2",
      "deckLanguagePlaceholder": "e.g., Spanish, Japanese, Armenian",
      "deckDescriptionPlaceholder": "What's in this deck?"
    },

    "cardList": {
      "back": "Back",
      "cardsTotal": "{n} cards total",
      "study": "Study",
      "addCard": "Add Card",
      "practiceCards": "Practice cards",
      "renameDeck": "Rename deck",
      "duplicateAsIs": "Duplicate as is",
      "duplicateAndFlip": "Duplicate and flip cards",
      "moveToProject": "Move to Project",
      "exportCSV": "Export CSV",
      "deleteDeck": "Delete deck",
      "searchCards": "Search cards...",
      "filter": "Filter",
      "filterAll": "All Cards",
      "filterDue": "Due Today",
      "filterNew": "New",
      "filterStarred": "Starred",
      "noCards": "No cards in this deck yet. Add your first card!",
      "noCardsFilter": "No cards match your filter.",
      "active": "Active",
      "word": "Word",
      "translation": "Translation",
      "status": "Status",
      "interval": "Interval",
      "addNewCard": "Add New Card",
      "addNewCardDesc": "Create a new flashcard for this deck.",
      "wordLabel": "{language} *",
      "wordPlaceholder": "e.g., el libro",
      "translationLabel": "Translation *",
      "translationPlaceholder": "e.g., книга",
      "sentenceLabel": "Example Sentence (optional)",
      "sentencePlaceholder": "Example sentence using this word",
      "associationLabel": "Association/Mnemonic (optional)",
      "associationPlaceholder": "Memory aid",
      "editCard": "Edit Card",
      "deleteCard": "Delete Card?",
      "deleteCardDesc": "This will permanently delete this card and its review history.",
      "renameDeckTitle": "Rename Deck",
      "moveTitle": "Move Deck",
      "moveDesc": "Move this deck to another project.",
      "moveSelect": "Select a project",
      "moveButton": "Move Deck",
      "moveError": "Failed to move deck",
      "failedToRenameDeck": "Failed to rename deck"
    },

    "flashcard": {
      "hintTitle": "How to use the card",
      "hintIntro": "Try to recall what's on the reverse and hit the button:",
      "hintAgain": "Again",
      "hintAgainDesc": "— Didn't remember. Will show up again soon.",
      "hintHard": "Hard",
      "hintHardDesc": "— Remembered, but with effort. Will appear more frequently.",
      "hintGood": "Good",
      "hintGoodDesc": "— Remembered well. On track.",
      "hintEasy": "Easy",
      "hintEasyDesc": "— Remembered instantly. Will appear much later.",
      "gotIt": "Got it",
      "statusNew": "New",
      "statusLearning": "Learning",
      "statusGraduated": "Graduated",
      "statusReview": "Review",
      "next": "Next: {interval}",
      "tapToReveal": "Tap to reveal",
      "example": "Example",
      "memory": "Memory"
    },

    "reviewSession": {
      "back": "Back",
      "sessionComplete": "Session Complete!",
      "reviewed": "Reviewed {n} cards",
      "accuracy": "Accuracy",
      "correct": "{n} correct",
      "backToDecks": "Back to Decks",
      "nothingDue": "Nothing due today!",
      "nothingDueDesc": "All caught up. Check back tomorrow or add new cards.",
      "cardProgress": "{current} / {total}"
    },

    "practiceSession": {
      "practiceMode": "Practice Mode",
      "back": "Back",
      "done": "Done",
      "noCards": "No cards in this deck to practice.",
      "cardProgress": "{current} / {total}"
    },

    "batchImport": {
      "title": "Batch Import",
      "subtitle": "Import multiple cards at once from a CSV file or paste directly.",
      "howToTitle": "How to import",
      "howToStep1": "1. Prepare a spreadsheet with columns: word, translation, sentence (optional), association (optional). This will be the structure of your deck. Each row represents a card, E.g.: book | книга | The book is on the table | reading material",
      "downloadTemplate": "Download CSV template",
      "howToStep2": "2. Save your spreadsheet as a .csv file. Upload the CSV or copy and paste it into the field above. If the decks aren't exporting correctly, try selecting another CSV separator.",
      "importCSVTitle": "Import CSV file",
      "targetDeck": "Target Deck *",
      "noDecksPlaceholder": "No decks yet — create one below",
      "selectDeckPlaceholder": "Select a deck",
      "createNewDeck": "Create new deck",
      "csvSeparator": "CSV Separator",
      "separatorHint": "If you get incorrect import results, try selecting a different separator.",
      "comma": "Comma (,)",
      "semicolon": "Semicolon (;)",
      "updateExisting": "Update existing cards",
      "updateExistingDesc": "If a card with the same word exists, update it",
      "uploadFile": "Upload CSV File",
      "clickToUpload": "Click to upload or drag and drop",
      "csvOrTxt": "CSV or TXT files",
      "pasteCsv": "Or paste CSV content directly",
      "errorTitle": "Error",
      "importComplete": "Import Complete",
      "importCompleteDesc": "{imported} cards imported, {updated} updated",
      "skipped": ", {n} skipped",
      "done": "Done",
      "cancelImport": "Cancel",
      "importCards": "Import Cards",
      "importing": "Importing...",
      "createNewDeckTitle": "Create New Deck",
      "deckCreatedDesc": "Now select your CSV file or paste the content below.",
      "nameLabel": "Name *",
      "languageLabel": "Language *",
      "descriptionLabel": "Description (optional)",
      "deckNamePlaceholder": "e.g., Week 2",
      "deckLanguagePlaceholder": "e.g., Spanish, Japanese, Armenian",
      "deckDescriptionPlaceholder": "What's in this deck?",
      "createDeck": "Create Deck"
    },

    "progress": {
      "title": "Progress Dashboard",
      "subtitle": "Track your learning progress",
      "totalCards": "Total Cards",
      "graduatedLearning": "{graduated} graduated, {learning} learning",
      "dueToday": "Due Today",
      "newAvailable": "{n} new cards available",
      "retentionRate": "Retention Rate",
      "fromReviews": "From {n} total reviews",
      "difficultCards": "Difficult Cards",
      "markedForPractice": "Marked for extra practice",
      "weeklyGoal": "Weekly Goal",
      "weeklyGoalDesc": "{learned} of {target} cards this week",
      "daysLeft": "{n} days left",
      "goalReached": "Goal reached! Great work this week!",
      "percentComplete": "{n}% complete",
      "dailyReviews": "Daily Reviews",
      "dailyReviewsDesc": "Cards reviewed over the past week",
      "accuracyTrend": "Accuracy Trend",
      "accuracyTrendDesc": "Correct answers over time",
      "difficultWordsTitle": "Difficult Words",
      "difficultWordsDesc": "Cards you've marked for extra practice"
    },

    "settings": {
      "title": "Project Settings",
      "projectNameTitle": "Project Name",
      "rename": "Rename",
      "save": "Save",
      "cancel": "Cancel",
      "weekendModeTitle": "Weekend Learner Mode",
      "weekendModeDesc": "Adjust your daily card limits based on the day of the week",
      "enableWeekendMode": "Enable weekend learner mode",
      "enableWeekendModeDesc": "Higher review load on weekends, lighter on weekdays",
      "weekdays": "Weekdays (Mon-Fri)",
      "weekends": "Weekends (Sat-Sun)",
      "newCardsPerDay": "New cards per day",
      "reviewCardsPerDay": "Review cards per day",
      "reviewPrefsTitle": "Review Preferences",
      "reviewPrefsDesc": "Customize how your review sessions work",
      "prioritizeStarred": "Prioritize starred cards",
      "prioritizeStarredDesc": "Show difficult (starred) cards first in review sessions",
      "weeklyTarget": "Weekly card target",
      "weeklyTargetDesc": "Goal for new cards to learn each week",
      "dataManagementTitle": "Data Management",
      "dataManagementDesc": "Export your data for backup",
      "currentData": "Current data: {decks} decks, {cards} cards, {reviews} reviews",
      "exportAll": "Export All Data (JSON)",
      "exportCards": "Export Cards (CSV)",
      "exportReviews": "Export Reviews (CSV)",
      "deleteProjectTitle": "Delete Project",
      "deleteProjectDesc": "Permanently delete \"{name}\" and all its decks, cards, and review history.",
      "deleteProjectOnlyOne": "You cannot delete your only project. Create another project first.",
      "deleteProject": "Delete Project",
      "settingsSaved": "Settings Saved",
      "saveSettings": "Save Settings",
      "deleteProjectConfirmTitle": "Delete Project?",
      "deleteProjectConfirmDesc": "This will permanently delete \"{name}\" and all its decks, cards, and review history. This action cannot be undone.",
      "projectRenamedTitle": "Project renamed",
      "projectRenamedDesc": "The project name has been updated.",
      "renameFailedTitle": "Rename failed",
      "settingsSavedTitle": "Settings saved",
      "settingsSavedDesc": "Your preferences have been updated.",
      "dataExportedTitle": "Data exported",
      "dataExportedDesc": "Your complete backup has been downloaded.",
      "cardsExportedTitle": "Cards exported",
      "cardsExportedDesc": "{n} cards exported to CSV.",
      "reviewsExportedTitle": "Reviews exported",
      "reviewsExportedDesc": "{n} review records exported to CSV.",
      "projectDeletedTitle": "Project deleted",
      "projectDeletedDesc": "The project and all its data have been removed."
    },

    "projectSelector": {
      "selectProject": "Select Project",
      "selectProjectDesc": "Switch between your learning projects.",
      "createProject": "Create Project",
      "createNewProject": "Create New Project",
      "createNewProjectDesc": "Projects help you organize different learning goals separately.",
      "projectNameLabel": "Project Name",
      "projectNamePlaceholder": "e.g., Spanish Course"
    },

    "addDeckPicker": {
      "title": "Add a deck",
      "createDeck": "Create a deck",
      "createDeckDesc": "Start from scratch",
      "importCSV": "Import CSV",
      "importCSVDesc": "Upload your own word list",
      "chooseLibrary": "Choose from Library",
      "chooseLibraryDesc": "Browse ready-made decks"
    },

    "onboarding": {
      "step1Title": "Spaced Repetition",
      "step1Desc": "Your brain remembers things better when you review them at increasing intervals, right before you're about to forget them.\n\nThis app uses this method to figure out the optimal moment to quiz you.",
      "step2Title": "Organize Your Learning",
      "step2Desc": "Use projects to organise your learning tracks, e.g., \"Chinese\", \"Spanish\", and set up a specific schedule for each.\n\nPlace 20-30 items into a single deck to smooth the learning curve.",
      "step3Title": "Learn Anywhere",
      "step3Desc": "Learn on a desktop or a mobile and track your project progress in the stats dashboard. Practice intensively by flipping the deck or using Weekend mode.\n\nHappy learning!",
      "skip": "Skip",
      "back": "Back",
      "next": "Next",
      "createADeck": "Create a deck"
    },

    "reviewGuard": {
      "title": "Do you want to interrupt the learning session?",
      "desc": "Your progress has been saved, by the way.",
      "stayHere": "Stay here",
      "interruptAndGo": "Interrupt and go"
    },

    "common": {
      "cancel": "Cancel",
      "save": "Save",
      "delete": "Delete",
      "confirm": "Confirm",
      "loading": "Loading..."
    }
  }
}